### ISSUE TITLE
Only one node is active the exporter

### ISSUE THREAD

**Issue by MalloZup** [SUSE/saptune_exporter#3]
The current status is that the exporter is running on HANA01 host.

If in future we want to run the saptune_exporter in each node the https://github.com/SUSE/ha-sap-terraform-deployments need some modification and also the related dashboard

**Comment by stefanotorresi** [comment]
I don't think this is related to the exporter itself! From the deployment side, this has been fixed in SUSE/ha-sap-terraform-deployments#608-
